/robot/onrobot_rg_gripper_controller:
  ros__parameters:
    type: position_controllers/GripperActionController
    default: true
    use_sim_time: true
    joint: robot_arm_rg6_finger_joint
    goal_tolerance: 0.01
    max_effort: 100.0
    action_monitor_rate: 20.0
    state_publish_rate: 50.0
