# Default initial positions for rbvogui_plus's ros2_control fake system

initial_positions:
  robot_arm_shoulder_pan_joint: -1.57
  robot_arm_shoulder_lift_joint: -1.57
  robot_arm_elbow_joint: 0.0
  robot_arm_wrist_1_joint: -1.57
  robot_arm_wrist_2_joint: 0.0
  robot_arm_wrist_3_joint: 0.0
